# 1. Create a 3x3x3 array with random values

1

2

In []:

In [13]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print('random_array',random_array)

random_array [[[0.2938289  0.35686842 0.48067134]
  [0.97540579 0.96091057 0.31451237]
  [0.42746356 0.48274383 0.49396246]]

 [[0.03667847 0.0990589  0.92614062]
  [0.24883462 0.58417213 0.43071709]
  [0.10253409 0.43382311 0.05490057]]

 [[0.03590925 0.98011696 0.77139897]
  [0.21441032 0.16194984 0.89671305]
  [0.9290799  0.95141602 0.44363609]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In []: 1


In [14]:
import numpy as np
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]: 1

In [16]:
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

1

In []:

In [19]:
import numpy as np
random_matrix = np.random.rand(5, 5)
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.37616828 0.94295212 0.27706004 0.02440212 0.88978216]
 [0.69999689 0.50700062 0.93512019 0.89402712 0.99392009]
 [0.13560054 0.50880027 0.49646461 0.51506257 0.37679741]
 [0.63676102 0.55231197 0.76901844 0.64634614 0.68178897]
 [0.15903916 0.0971391  0.31733133 0.90414215 0.16045305]]

Normalized Matrix:
[[-0.56288486  1.38563864 -0.90360513 -1.77220768  1.20284776]
 [ 0.55039257 -0.1131016   1.35871356  1.21744135  1.5608594 ]
 [-1.38992307 -0.10691464 -0.14932292 -0.08538574 -0.56072198]
 [ 0.33299651  0.04267248  0.78767902  0.36594879  0.4877963 ]
 [-1.3093444  -1.52214813 -0.76515804  1.25221541 -1.30448361]]


# 5. How to find common values between two arrays?

In []: 1

In [1]:
import numpy as np
random_matrix = np.random.rand(4, 3)
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.22791114 0.09736934 0.1977417 ]
 [0.97301513 0.17462444 0.92827716]
 [0.97420436 0.5852987  0.15062562]
 [0.59629935 0.21437862 0.45080203]]

Normalized Matrix:
[[-0.72560777 -1.12646126 -0.81824879]
 [ 1.56237614 -0.88923475  1.42499967]
 [ 1.56602787  0.37181888 -0.96292771]
 [ 0.40559847 -0.76716196 -0.04117879]]


# 6. How to get the dates of yesterday, today and tomorrow?

In [ ]: 1

In [10]:
from datetime import datetime, timedelta

today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20 14:36:22.051502
Today: 2023-09-21 14:36:22.051502
Tomorrow: 2023-09-22 14:36:22.051502


# 7. Consider two random array A and B, check if they are equal


In [25]:
import numpy as np
A = np.random.rand(98, 5)
B = np.random.rand(5, 5)
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In []: 1

In [27]:
import numpy as np
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced:")
print(random_vector)


Random Vector with Maximum Value Replaced:
[0.29350329 0.6061975  0.         0.60131837 0.07433782 0.73961935
 0.87672628 0.24771798 0.59586846 0.41070136]


# 9. How to print all the values of an array?

In []: 1

In [28]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [ ]: 1

In [32]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_means = np.mean(matrix, axis=1, keepdims=True)
matrix_minus_mean = matrix - row_means

print(matrix_minus_mean)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In []:  1

In [ ]: 1


In [34]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_means = np.mean(matrix, axis=1, keepdims=True)
matrix_minus_mean = matrix - row_means

print(matrix_minus_mean)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 12.How to get the diagonal of a dot product?

In []: 1

In [35]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
dot_product = np.dot(matrix1, matrix2)
diagonal_elements = np.diagonal(dot_product)

print(diagonal_elements)


[30 69 90]


# 13. How to find the most frequent value in an array?

In [3]: 1 x = np.random.randint(0,10,58)

2 x Out [3]: array([7, 4, 5, 3, 3, 6, 5, 8, 1, 5, 1, 1, 8, 7, 4, 5, 8, 7, 3, 2, 3, 6, 1, 5, 3, 3, 7, 5, 0, 3, 8, 7, 1, 4, 1, 4, 1, 1, 1, 6, 6, 8, 6, 8, 3, 4, 4, 7, 8, 0])

In [36]:
import numpy as np
x = np.random.randint(0, 10, 58)
most_frequent_value = np.bincount(x).argmax()

print(f"The most frequent value is: {most_frequent_value}")


The most frequent value is: 3


# 14. How to get the n largest values of an array

In []: 1

In []: 1

In [37]:
import numpy as np
arr = np.array([4, 2, 9, 7, 5, 1, 8, 3, 6])
n = 3
partitioned = np.partition(arr, -n)
n_largest = partitioned[-n:]

print(f"The {n} largest values are: {n_largest}")


The 3 largest values are: [7 9 8]


# 15. How to create a record array from a regular array?


In [38]:
import numpy as np
regular_array = np.array([(1, 'Roman', 25),
                          (2, 'Tushar', 30),
                          (3, 'mannat', 35)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])
record_array = np.rec.array(regular_array)
print(record_array.id)  
print(record_array.name) 
print(record_array.age)  


[1 2 3]
['Roman' 'Tushar' 'mannat']
[25 30 35]


# 16. How to swap two rows of an array?

In []: 1

In [ ]: 1


In [39]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
row1 = 0 
row2 = 1 
temp_row = array[row1].copy()

array[row1] = array[row2]
array[row2] = temp_row

print("Array after swapping rows:")
print(array)



Array after swapping rows:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [2]: 1 x=np.array([[23,34,121][23,22,67][686,434,123]]) 2 x

Out [2]: array([[ 23, 34, 121],

[23, 22, 67), [686, 434, 123]])

In []: 1

In []: 1

In []: 1

In [40]:
import numpy as np

x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])


In [41]:

reshaped_x = x.reshape(x.shape[0], x.shape[1], 1)

print(reshaped_x)


[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
